### ISSUE TITLE
Theme Resource Support over Hard-coded colors (Dark Theme Issue)

### ISSUE THREAD

**Issue by michael-hawker** [kyralee22/MetaverseUIContent#1]
If your machine is set to Dark Mode then the app isn't readible:

![image](https://user-images.githubusercontent.com/24302614/184721421-fe3deccc-2f2d-4abf-b9bf-584b6180b1a7.png)

vs. light-mode enabled (Windows 10):

![image](https://user-images.githubusercontent.com/24302614/184721867-278f72c5-e21d-4584-bae2-b562ca9f038b.png)

This is going to be because of hard-coded color values, like this:

https://github.com/kyralee22/MetaverseUIContent/blob/4a890c6465fb9090932f927f4bce24da526e7ec3/MetaverseUIContentWinUI/MainWindow.xaml#L11

Over the use of `ThemeResource` brushes. [See doc page here](https://docs.microsoft.com/en-us/windows/apps/design/style/color).

@niels9001 can probably suggest the best ones to use here or look at the [Toolkit Labs pages like this one](https://github.com/CommunityToolkit/Labs-Windows/blob/main/common/CommunityToolkit.Labs.Shared/Pages/GettingStartedPage.xaml).

**Comment by kyralee22** [comment]
Should work with dark mode now. Colors reflective of what the component will look like in dark mode in Unity.
